[package]
name = "s1-ffmpeg-pipe"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
cc = { path = "../cc" }
ffmpeg-next = { version = "9.0.0", default-features = false, features = ["format", "codec"] }
